//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Registro.Maquina {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MaquinaVendingSoap11Binding", Namespace="http://Maquina")]
    public partial class MaquinaVending : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback displayOperationCompleted;
        
        private System.Threading.SendOrPostCallback setNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerLineaOperationCompleted;
        
        private System.Threading.SendOrPostCallback leerFicheroOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMonederoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InicializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback getNombreOperationCompleted;
        
        private System.Threading.SendOrPostCallback escribeFicheroOperationCompleted;
        
        private System.Threading.SendOrPostCallback setFechaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTemperaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback setMonederoOperationCompleted;
        
        private System.Threading.SendOrPostCallback setEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback setTemperaturaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MaquinaVending() {
            this.Url = global::Registro.Properties.Settings.Default.Registro_Maquina_MaquinaVending;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getFechaCompletedEventHandler getFechaCompleted;
        
        /// <remarks/>
        public event setStockCompletedEventHandler setStockCompleted;
        
        /// <remarks/>
        public event displayCompletedEventHandler displayCompleted;
        
        /// <remarks/>
        public event setNombreCompletedEventHandler setNombreCompleted;
        
        /// <remarks/>
        public event getEstadoCompletedEventHandler getEstadoCompleted;
        
        /// <remarks/>
        public event leerLineaCompletedEventHandler leerLineaCompleted;
        
        /// <remarks/>
        public event leerFicheroCompletedEventHandler leerFicheroCompleted;
        
        /// <remarks/>
        public event getMonederoCompletedEventHandler getMonederoCompleted;
        
        /// <remarks/>
        public event InicializarCompletedEventHandler InicializarCompleted;
        
        /// <remarks/>
        public event getNombreCompletedEventHandler getNombreCompleted;
        
        /// <remarks/>
        public event escribeFicheroCompletedEventHandler escribeFicheroCompleted;
        
        /// <remarks/>
        public event setFechaCompletedEventHandler setFechaCompleted;
        
        /// <remarks/>
        public event getStockCompletedEventHandler getStockCompleted;
        
        /// <remarks/>
        public event getTemperaturaCompletedEventHandler getTemperaturaCompleted;
        
        /// <remarks/>
        public event setMonederoCompletedEventHandler setMonederoCompleted;
        
        /// <remarks/>
        public event setEstadoCompletedEventHandler setEstadoCompleted;
        
        /// <remarks/>
        public event setTemperaturaCompletedEventHandler setTemperaturaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getFecha", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getFechaResponse", Namespace="http://Maquina")]
        public getFechaResponse getFecha() {
            object[] results = this.Invoke("getFecha", new object[0]);
            return ((getFechaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getFechaAsync() {
            this.getFechaAsync(null);
        }
        
        /// <remarks/>
        public void getFechaAsync(object userState) {
            if ((this.getFechaOperationCompleted == null)) {
                this.getFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFechaOperationCompleted);
            }
            this.InvokeAsync("getFecha", new object[0], this.getFechaOperationCompleted, userState);
        }
        
        private void OngetFechaOperationCompleted(object arg) {
            if ((this.getFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFechaCompleted(this, new getFechaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setStock", RequestNamespace="http://Maquina", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setStock(int valor, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valorSpecified) {
            this.Invoke("setStock", new object[] {
                        valor,
                        valorSpecified});
        }
        
        /// <remarks/>
        public void setStockAsync(int valor, bool valorSpecified) {
            this.setStockAsync(valor, valorSpecified, null);
        }
        
        /// <remarks/>
        public void setStockAsync(int valor, bool valorSpecified, object userState) {
            if ((this.setStockOperationCompleted == null)) {
                this.setStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetStockOperationCompleted);
            }
            this.InvokeAsync("setStock", new object[] {
                        valor,
                        valorSpecified}, this.setStockOperationCompleted, userState);
        }
        
        private void OnsetStockOperationCompleted(object arg) {
            if ((this.setStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setStockCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:display", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("displayResponse", Namespace="http://Maquina")]
        public displayResponse display() {
            object[] results = this.Invoke("display", new object[0]);
            return ((displayResponse)(results[0]));
        }
        
        /// <remarks/>
        public void displayAsync() {
            this.displayAsync(null);
        }
        
        /// <remarks/>
        public void displayAsync(object userState) {
            if ((this.displayOperationCompleted == null)) {
                this.displayOperationCompleted = new System.Threading.SendOrPostCallback(this.OndisplayOperationCompleted);
            }
            this.InvokeAsync("display", new object[0], this.displayOperationCompleted, userState);
        }
        
        private void OndisplayOperationCompleted(object arg) {
            if ((this.displayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.displayCompleted(this, new displayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setNombre", RequestNamespace="http://Maquina", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setNombre([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string valor) {
            this.Invoke("setNombre", new object[] {
                        valor});
        }
        
        /// <remarks/>
        public void setNombreAsync(string valor) {
            this.setNombreAsync(valor, null);
        }
        
        /// <remarks/>
        public void setNombreAsync(string valor, object userState) {
            if ((this.setNombreOperationCompleted == null)) {
                this.setNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetNombreOperationCompleted);
            }
            this.InvokeAsync("setNombre", new object[] {
                        valor}, this.setNombreOperationCompleted, userState);
        }
        
        private void OnsetNombreOperationCompleted(object arg) {
            if ((this.setNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setNombreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getEstado", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getEstadoResponse", Namespace="http://Maquina")]
        public getEstadoResponse getEstado() {
            object[] results = this.Invoke("getEstado", new object[0]);
            return ((getEstadoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getEstadoAsync() {
            this.getEstadoAsync(null);
        }
        
        /// <remarks/>
        public void getEstadoAsync(object userState) {
            if ((this.getEstadoOperationCompleted == null)) {
                this.getEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEstadoOperationCompleted);
            }
            this.InvokeAsync("getEstado", new object[0], this.getEstadoOperationCompleted, userState);
        }
        
        private void OngetEstadoOperationCompleted(object arg) {
            if ((this.getEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEstadoCompleted(this, new getEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:leerLinea", RequestNamespace="http://Maquina", ResponseNamespace="http://Maquina", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string leerLinea(int numero, [System.Xml.Serialization.XmlIgnoreAttribute()] bool numeroSpecified) {
            object[] results = this.Invoke("leerLinea", new object[] {
                        numero,
                        numeroSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void leerLineaAsync(int numero, bool numeroSpecified) {
            this.leerLineaAsync(numero, numeroSpecified, null);
        }
        
        /// <remarks/>
        public void leerLineaAsync(int numero, bool numeroSpecified, object userState) {
            if ((this.leerLineaOperationCompleted == null)) {
                this.leerLineaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerLineaOperationCompleted);
            }
            this.InvokeAsync("leerLinea", new object[] {
                        numero,
                        numeroSpecified}, this.leerLineaOperationCompleted, userState);
        }
        
        private void OnleerLineaOperationCompleted(object arg) {
            if ((this.leerLineaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerLineaCompleted(this, new leerLineaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:leerFichero", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("leerFicheroResponse", Namespace="http://Maquina")]
        public leerFicheroResponse leerFichero() {
            object[] results = this.Invoke("leerFichero", new object[0]);
            return ((leerFicheroResponse)(results[0]));
        }
        
        /// <remarks/>
        public void leerFicheroAsync() {
            this.leerFicheroAsync(null);
        }
        
        /// <remarks/>
        public void leerFicheroAsync(object userState) {
            if ((this.leerFicheroOperationCompleted == null)) {
                this.leerFicheroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnleerFicheroOperationCompleted);
            }
            this.InvokeAsync("leerFichero", new object[0], this.leerFicheroOperationCompleted, userState);
        }
        
        private void OnleerFicheroOperationCompleted(object arg) {
            if ((this.leerFicheroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.leerFicheroCompleted(this, new leerFicheroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getMonedero", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getMonederoResponse", Namespace="http://Maquina")]
        public getMonederoResponse getMonedero() {
            object[] results = this.Invoke("getMonedero", new object[0]);
            return ((getMonederoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getMonederoAsync() {
            this.getMonederoAsync(null);
        }
        
        /// <remarks/>
        public void getMonederoAsync(object userState) {
            if ((this.getMonederoOperationCompleted == null)) {
                this.getMonederoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMonederoOperationCompleted);
            }
            this.InvokeAsync("getMonedero", new object[0], this.getMonederoOperationCompleted, userState);
        }
        
        private void OngetMonederoOperationCompleted(object arg) {
            if ((this.getMonederoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMonederoCompleted(this, new getMonederoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:Inicializar", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void Inicializar() {
            this.Invoke("Inicializar", new object[0]);
        }
        
        /// <remarks/>
        public void InicializarAsync() {
            this.InicializarAsync(null);
        }
        
        /// <remarks/>
        public void InicializarAsync(object userState) {
            if ((this.InicializarOperationCompleted == null)) {
                this.InicializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInicializarOperationCompleted);
            }
            this.InvokeAsync("Inicializar", new object[0], this.InicializarOperationCompleted, userState);
        }
        
        private void OnInicializarOperationCompleted(object arg) {
            if ((this.InicializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InicializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getNombre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getNombreResponse", Namespace="http://Maquina")]
        public getNombreResponse getNombre() {
            object[] results = this.Invoke("getNombre", new object[0]);
            return ((getNombreResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getNombreAsync() {
            this.getNombreAsync(null);
        }
        
        /// <remarks/>
        public void getNombreAsync(object userState) {
            if ((this.getNombreOperationCompleted == null)) {
                this.getNombreOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetNombreOperationCompleted);
            }
            this.InvokeAsync("getNombre", new object[0], this.getNombreOperationCompleted, userState);
        }
        
        private void OngetNombreOperationCompleted(object arg) {
            if ((this.getNombreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getNombreCompleted(this, new getNombreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:escribeFichero", RequestNamespace="http://Maquina", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void escribeFichero([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] object datos, int opcion, [System.Xml.Serialization.XmlIgnoreAttribute()] bool opcionSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string numero) {
            this.Invoke("escribeFichero", new object[] {
                        datos,
                        opcion,
                        opcionSpecified,
                        numero});
        }
        
        /// <remarks/>
        public void escribeFicheroAsync(object datos, int opcion, bool opcionSpecified, string numero) {
            this.escribeFicheroAsync(datos, opcion, opcionSpecified, numero, null);
        }
        
        /// <remarks/>
        public void escribeFicheroAsync(object datos, int opcion, bool opcionSpecified, string numero, object userState) {
            if ((this.escribeFicheroOperationCompleted == null)) {
                this.escribeFicheroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnescribeFicheroOperationCompleted);
            }
            this.InvokeAsync("escribeFichero", new object[] {
                        datos,
                        opcion,
                        opcionSpecified,
                        numero}, this.escribeFicheroOperationCompleted, userState);
        }
        
        private void OnescribeFicheroOperationCompleted(object arg) {
            if ((this.escribeFicheroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.escribeFicheroCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setFecha", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void setFecha() {
            this.Invoke("setFecha", new object[0]);
        }
        
        /// <remarks/>
        public void setFechaAsync() {
            this.setFechaAsync(null);
        }
        
        /// <remarks/>
        public void setFechaAsync(object userState) {
            if ((this.setFechaOperationCompleted == null)) {
                this.setFechaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetFechaOperationCompleted);
            }
            this.InvokeAsync("setFecha", new object[0], this.setFechaOperationCompleted, userState);
        }
        
        private void OnsetFechaOperationCompleted(object arg) {
            if ((this.setFechaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setFechaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getStock", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getStockResponse", Namespace="http://Maquina")]
        public getStockResponse getStock() {
            object[] results = this.Invoke("getStock", new object[0]);
            return ((getStockResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getStockAsync() {
            this.getStockAsync(null);
        }
        
        /// <remarks/>
        public void getStockAsync(object userState) {
            if ((this.getStockOperationCompleted == null)) {
                this.getStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockOperationCompleted);
            }
            this.InvokeAsync("getStock", new object[0], this.getStockOperationCompleted, userState);
        }
        
        private void OngetStockOperationCompleted(object arg) {
            if ((this.getStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockCompleted(this, new getStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getTemperatura", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("getTemperaturaResponse", Namespace="http://Maquina")]
        public getTemperaturaResponse getTemperatura() {
            object[] results = this.Invoke("getTemperatura", new object[0]);
            return ((getTemperaturaResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getTemperaturaAsync() {
            this.getTemperaturaAsync(null);
        }
        
        /// <remarks/>
        public void getTemperaturaAsync(object userState) {
            if ((this.getTemperaturaOperationCompleted == null)) {
                this.getTemperaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTemperaturaOperationCompleted);
            }
            this.InvokeAsync("getTemperatura", new object[0], this.getTemperaturaOperationCompleted, userState);
        }
        
        private void OngetTemperaturaOperationCompleted(object arg) {
            if ((this.getTemperaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTemperaturaCompleted(this, new getTemperaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setMonedero", RequestNamespace="http://Maquina", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setMonedero(int valor, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valorSpecified) {
            this.Invoke("setMonedero", new object[] {
                        valor,
                        valorSpecified});
        }
        
        /// <remarks/>
        public void setMonederoAsync(int valor, bool valorSpecified) {
            this.setMonederoAsync(valor, valorSpecified, null);
        }
        
        /// <remarks/>
        public void setMonederoAsync(int valor, bool valorSpecified, object userState) {
            if ((this.setMonederoOperationCompleted == null)) {
                this.setMonederoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetMonederoOperationCompleted);
            }
            this.InvokeAsync("setMonedero", new object[] {
                        valor,
                        valorSpecified}, this.setMonederoOperationCompleted, userState);
        }
        
        private void OnsetMonederoOperationCompleted(object arg) {
            if ((this.setMonederoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setMonederoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setEstado", RequestNamespace="http://Maquina", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setEstado(int valor, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valorSpecified) {
            this.Invoke("setEstado", new object[] {
                        valor,
                        valorSpecified});
        }
        
        /// <remarks/>
        public void setEstadoAsync(int valor, bool valorSpecified) {
            this.setEstadoAsync(valor, valorSpecified, null);
        }
        
        /// <remarks/>
        public void setEstadoAsync(int valor, bool valorSpecified, object userState) {
            if ((this.setEstadoOperationCompleted == null)) {
                this.setEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetEstadoOperationCompleted);
            }
            this.InvokeAsync("setEstado", new object[] {
                        valor,
                        valorSpecified}, this.setEstadoOperationCompleted, userState);
        }
        
        private void OnsetEstadoOperationCompleted(object arg) {
            if ((this.setEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setEstadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setTemperatura", RequestNamespace="http://Maquina", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setTemperatura(int valor, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valorSpecified) {
            this.Invoke("setTemperatura", new object[] {
                        valor,
                        valorSpecified});
        }
        
        /// <remarks/>
        public void setTemperaturaAsync(int valor, bool valorSpecified) {
            this.setTemperaturaAsync(valor, valorSpecified, null);
        }
        
        /// <remarks/>
        public void setTemperaturaAsync(int valor, bool valorSpecified, object userState) {
            if ((this.setTemperaturaOperationCompleted == null)) {
                this.setTemperaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTemperaturaOperationCompleted);
            }
            this.InvokeAsync("setTemperatura", new object[] {
                        valor,
                        valorSpecified}, this.setTemperaturaOperationCompleted, userState);
        }
        
        private void OnsetTemperaturaOperationCompleted(object arg) {
            if ((this.setTemperaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTemperaturaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class getFechaResponse {
        
        private string returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class displayResponse {
        
        private string returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class getEstadoResponse {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <comentarios/>
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class leerFicheroResponse {
        
        private object returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class getMonederoResponse {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <comentarios/>
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class getNombreResponse {
        
        private string returnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class getStockResponse {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <comentarios/>
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Maquina")]
    public partial class getTemperaturaResponse {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <comentarios/>
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getFechaCompletedEventHandler(object sender, getFechaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFechaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFechaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getFechaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getFechaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setStockCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void displayCompletedEventHandler(object sender, displayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class displayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal displayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public displayResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((displayResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setNombreCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getEstadoCompletedEventHandler(object sender, getEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getEstadoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getEstadoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void leerLineaCompletedEventHandler(object sender, leerLineaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerLineaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerLineaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void leerFicheroCompletedEventHandler(object sender, leerFicheroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class leerFicheroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal leerFicheroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public leerFicheroResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((leerFicheroResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getMonederoCompletedEventHandler(object sender, getMonederoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMonederoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMonederoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getMonederoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getMonederoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void InicializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getNombreCompletedEventHandler(object sender, getNombreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getNombreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getNombreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getNombreResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getNombreResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void escribeFicheroCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setFechaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getStockCompletedEventHandler(object sender, getStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getStockResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getStockResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void getTemperaturaCompletedEventHandler(object sender, getTemperaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTemperaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTemperaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public getTemperaturaResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((getTemperaturaResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setMonederoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setEstadoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setTemperaturaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591